### ISSUE TITLE
Setting BA on deleted user's post causes 500 error

### ISSUE THREAD

**Issue by davwheat** [FriendsOfFlarum/best-answer#15]
### Log
```
[2020-06-04 21:42:44] production.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Return value of FoF\BestAnswer\Jobs\SendNotificationWhenBestAnswerSetInDiscussion::getUserFromPost() must be an instance of Flarum\User\User, null returned in /var/www/vendor/fof/best-answer/src/Jobs/SendNotificationWhenBestAnswerSetInDiscussion.php:71
Stack trace:
#0 /var/www/vendor/fof/best-answer/src/Jobs/SendNotificationWhenBestAnswerSetInDiscussion.php(54): FoF\BestAnswer\Jobs\SendNotificationWhenBestAnswerSetInDiscussion->getUserFromPost(14843)
#1 [internal function]: FoF\BestAnswer\Jobs\SendNotificationWhenBestAnswerSetInDiscussion->handle(Object(Flarum\Notification\NotificationSyncer))
#2 /var/www/vendor/illuminate/container/BoundMethod.php(29): call_user_func_array(Array, Array)
#3 /var/www/vendor/illuminate/container/BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#4 /var/www/vendor/illuminate/container/BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Flarum\Foundation\Application), Array, Object(Closure))
#5 /var/www/vendor/illuminate/container/Container.php(572): Illuminate\Container\BoundMethod::call(Object(Flarum\Foundation\Application), Array, Array, NULL)
#6 /var/www/vendor/illuminate/bus/Dispatcher.php(94): Illuminate\Container\Container->call(Array)
#7 /var/www/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(FoF\BestAnswer\Jobs\SendNotificationWhenBestAnswerSetInDiscussion))
#8 /var/www/vendor/illuminate/pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(FoF\BestAnswer\Jobs\SendNotificationWhenBestAnswerSetInDiscussion))
#9 /var/www/vendor/illuminate/bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#10 /var/www/vendor/illuminate/queue/CallQueuedHandler.php(49): Illuminate\Bus\Dispatcher->dispatchNow(Object(FoF\BestAnswer\Jobs\SendNotificationWhenBestAnswerSetInDiscussion), false)
#11 /var/www/vendor/illuminate/queue/Jobs/Job.php(83): Illuminate\Queue\CallQueuedHandler->call(Object(Illuminate\Queue\Jobs\SyncJob), Array)
#12 /var/www/vendor/illuminate/queue/SyncQueue.php(42): Illuminate\Queue\Jobs\Job->fire()
#13 /var/www/vendor/fof/best-answer/src/Listeners/QueueNotificationJobs.php(22): Illuminate\Queue\SyncQueue->push(Object(FoF\BestAnswer\Jobs\SendNotificationWhenBestAnswerSetInDiscussion))
#14 [internal function]: FoF\BestAnswer\Listeners\QueueNotificationJobs->handle(Object(FoF\BestAnswer\Events\BestAnswerSet))
#15 /var/www/vendor/illuminate/events/Dispatcher.php(379): call_user_func_array(Array, Array)
#16 /var/www/vendor/illuminate/events/Dispatcher.php(209): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('FoF\\BestAnswer\\...', Array)
#17 /var/www/vendor/fof/best-answer/src/Listeners/SelectBestAnswer.php(92): Illuminate\Events\Dispatcher->dispatch('FoF\\BestAnswer\\...')
#18 /var/www/vendor/flarum/core/src/Database/AbstractModel.php(65): FoF\BestAnswer\Listeners\SelectBestAnswer->FoF\BestAnswer\Listeners\{closure}(Object(Flarum\Discussion\Discussion))
#19 /var/www/vendor/illuminate/events/Dispatcher.php(360): Flarum\Database\AbstractModel::Flarum\Database\{closure}(Object(Flarum\Discussion\Discussion))
#20 /var/www/vendor/illuminate/events/Dispatcher.php(209): Illuminate\Events\Dispatcher->Illuminate\Events\{closure}('eloquent.saved:...', Array)
#21 /var/www/vendor/illuminate/database/Eloquent/Concerns/HasEvents.php(162): Illuminate\Events\Dispatcher->dispatch('eloquent.saved:...', Array)
#22 /var/www/vendor/illuminate/database/Eloquent/Model.php(692): Illuminate\Database\Eloquent\Model->fireModelEvent('saved', false)
#23 /var/www/vendor/illuminate/database/Eloquent/Model.php(663): Illuminate\Database\Eloquent\Model->finishSave(Array)
#24 /var/www/vendor/flarum/core/src/Discussion/Command/EditDiscussionHandler.php(82): Illuminate\Database\Eloquent\Model->save()
#25 /var/www/vendor/illuminate/bus/Dispatcher.php(90): Flarum\Discussion\Command\EditDiscussionHandler->handle(Object(Flarum\Discussion\Command\EditDiscussion))
#26 /var/www/vendor/illuminate/pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}(Object(Flarum\Discussion\Command\EditDiscussion))
#27 /var/www/vendor/illuminate/pipeline/Pipeline.php(104): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Flarum\Discussion\Command\EditDiscussion))
#28 /var/www/vendor/illuminate/bus/Dispatcher.php(98): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 /var/www/vendor/illuminate/bus/Dispatcher.php(76): Illuminate\Bus\Dispatcher->dispatchNow(Object(Flarum\Discussion\Command\EditDiscussion))
#30 /var/www/vendor/flarum/core/src/Api/Controller/UpdateDiscussionController.php(51): Illuminate\Bus\Dispatcher->dispatch(Object(Flarum\Discussion\Command\EditDiscussion))
#31 /var/www/vendor/flarum/core/src/Api/Controller/AbstractSerializeController.php(96): Flarum\Api\Controller\UpdateDiscussionController->data(Object(Laminas\Diactoros\ServerRequest), Object(Tobscure\JsonApi\Document))
#32 /var/www/vendor/flarum/core/src/Http/RouteHandlerFactory.php(38): Flarum\Api\Controller\AbstractSerializeController->handle(Object(Laminas\Diactoros\ServerRequest))
#33 /var/www/vendor/flarum/core/src/Http/Middleware/DispatchRoute.php(65): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}(Object(Laminas\Diactoros\ServerRequest), Array)
#34 /var/www/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\DispatchRoute->process(Object(Laminas\Diactoros\ServerRequest), Object(Closure))
#35 /var/www/vendor/flarum/core/src/Http/Middleware/SetLocale.php(50): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#36 /var/www/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\SetLocale->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#37 /var/www/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(45): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#38 /var/www/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\CheckCsrfToken->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#39 /var/www/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(55): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#40 /var/www/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithHeader->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#41 /var/www/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(32): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#42 /var/www/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\AuthenticateWithSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#43 /var/www/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(51): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#44 /var/www/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\RememberFromCookie->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#45 /var/www/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#46 /var/www/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\StartSession->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#47 /var/www/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#48 /var/www/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Api\Middleware\FakeHttpMethods->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#49 /var/www/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#50 /var/www/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\ParseJsonBody->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#51 /var/www/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#52 /var/www/vendor/laminas/laminas-stratigility/src/Next.php(61): Flarum\Http\Middleware\HandleErrors->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#53 /var/www/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#54 /var/www/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#55 /var/www/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\RequestHandler->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#56 /var/www/vendor/middlewares/base-path-router/src/BasePathRouter.php(97): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#57 /var/www/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePathRouter->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#58 /var/www/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(42): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#59 /var/www/vendor/laminas/laminas-stratigility/src/Next.php(61): Laminas\Stratigility\Middleware\OriginalMessages->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#60 /var/www/vendor/middlewares/base-path/src/BasePath.php(53): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#61 /var/www/vendor/laminas/laminas-stratigility/src/Next.php(61): Middlewares\BasePath->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\Next))
#62 /var/www/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(84): Laminas\Stratigility\Next->handle(Object(Laminas\Diactoros\ServerRequest))
#63 /var/www/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(73): Laminas\Stratigility\MiddlewarePipe->process(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Stratigility\EmptyPipelineHandler))
#64 /var/www/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(96): Laminas\Stratigility\MiddlewarePipe->handle(Object(Laminas\Diactoros\ServerRequest))
#65 /var/www/vendor/flarum/core/src/Http/Server.php(42): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#66 /var/www/public/index.php(26): Flarum\Http\Server->listen()
#67 {main}  
```

**Comment by datitisev** [comment]
Can you provide us with an error ? It should be found in storage/logs/flarum-<date>.log

**Comment by davwheat** [comment]
Yep, updated OP.

**Comment by datitisev** [comment]
Thank you.

**Comment by imorland** [comment]
This _should_ be resolved in the next release, so I'll close this issue now. Feel free to re-open if the issue persists!
